#!/usr/bin/env bash

case $button in
    1)
        xscreensaver-command -activate >/dev/null
        ;;

    3)
        /home/jacob/code/dotfiles/bin/keylight cycle
        ;;

    4)
        /home/jacob/code/dotfiles/bin/backlight -
        ;;

    5)
        /home/jacob/code/dotfiles/bin/backlight +
        ;;
esac

source ~/bin/_util

pango_color "orange" "<span weight='bold'></span> $(printf "%.0f%%" "$(xbacklight)")"
