#!/usr/bin/env bash

case $BLOCK_BUTTON in
    4)
        /home/jacob/code/dotfiles/bin/backlight -
        ;;

    5)
        /home/jacob/code/dotfiles/bin/backlight +
        ;;
esac

printf " %.0f%%" $(xbacklight)
