#!/usr/bin/env bash

# Respond to buttons first so as to avoid future calculations
case $button in
    1)
        terminal --command "sudo powertop"
        ;;
esac

source=/sys/class/power_supply/BAT0/

prop () {
  cat $source/$1
}

colorize () {
  echo "<span foreground=\"$1\">$2</span>"
}

start_nagbar() {
    i3-nagbar -m "Low Battery" >/dev/null 2>&1 &
}

kill_nagbar() {
    pkill -f "i3-nagbar -m Low Battery" >/dev/null
}

nagbar_running() {
    pgrep -f "i3-nagbar -m Low Battery" >/dev/null
}

alert () {
    nagbar_running || start_nagbar
}

clear_alert() {
    nagbar_running && kill_nagbar;
}

color () {
    local p=$1
    if [ "$p" -gt "50" ]; then
        local red=$(bc -l <<< "255 * 2 * (1 - ($p/100))")
        local green=255
    else
        local red=255
        local green=$(bc -l <<< "255 * 2 * ($p/100)")
    fi
    echo "#$(/home/jacob/code/dotfiles/bin/num2hex $red $green 0)"
}

# Ensure that $3 is at least $1 and at most $2
within_range() {
    minl=$1
    maxl=$2
    val=$3

    min=$(( $val < $minl ? $minl : $val))
    echo $(( $val > $maxl ? $maxl : $val))
}


# Create a scale between $1 and $2, and provide a percentage value
# corresponding to $3's position in that scale.
for_range() {
    best=$1
    worst=$2
    value=$3

    bc <<< "(100 * ($value - $worst) / ($best - $worst))/1"
}

charge_formula="$(prop energy_now) / $(prop energy_full) * 100"
charge=$(within_range 0 100 $(bc -l <<< $charge_formula | sed -e 's/\..*//'))

remaining=$(acpi | awk '{printf $5}' | cut -d':' -f 1-2 | sed 's/^0//')
power=$(printf "%.1f" $(bc -l <<< "$(prop power_now) / 1000000"))

# The power percentage is the value of the current rate as a percentage of the
# scale from 6 to 13, then capped at 0 and 100.
power_percent=$(within_range 0 100 $(for_range 6 13 $power))

charge_color=$(color $charge)
power_color=$(color $power_percent)

[ "$charge" -gt "7" ] && clear_alert;

if [ "$(prop status)" == "Charging" ]; then
   icon=""
   charge_color='#FFFF00'
   power_color='#FFFF00'
   clear_alert
elif [ "$charge" -gt "90" ]; then
  icon=""
elif [ "$charge" -gt "50" ]; then
  icon=""
elif [ "$charge" -gt "35" ]; then
  icon=""
elif [ "$charge" -gt "7" ]; then
  icon=""
else
  icon=""
  alert
fi

charge=$(colorize "$charge_color" "$icon $charge%")
power=$(colorize $power_color "$power W")

echo -n "$charge $remaining $power"
