#!/usr/bin/env bash

case $BLOCK_BUTTON in
    1)
        gnome-terminal --command "htop"
        ;;
esac

usage=$(grep 'cpu ' /proc/stat | awk '{printf "%.1f%", (($2+$4)*100)/($2+$4+$5)}')

temp=$(awk '{printf "%.1f°F", ($1 / 1000) * (9/5) + 32}' /sys/class/thermal/thermal_zone0/temp)

echo "$usage $temp"
