#!/usr/bin/env bash

[ -e /tmp/low_power_mode ] && exit 0

case $button in
    1)
        terminal --command "ncdu" --directory "/home/$(whoami)"
        ;;
esac

usage=$(df -B M | grep " /$" | awk '{print $3/1}')
usage=$(echo "scale=1; $usage/1024" | bc -l)

source ~/bin/_util
pango_color "pink cocktail" "<span weight='bold'></span> $usage Gb"
