#!/usr/bin/env bash

case $button in
    1)
        /home/jacob/code/go/bin/mw play-pause
        ;;
esac

leafy="#53D462"
grey="#666666"
lightgrey="#424242"

# status=$(/home/jacob/code/dotfiles/bin/music status-line)
/home/jacob/code/go/bin/mw status -watch \
  -format '<span foreground="{status}">{icon} {artist} :: {track}</span>' \
  | sed --unbuffered -e "s/Paused/$grey/" -e "s/Playing/$leafy/" \
                     -e "s/Stopped/$lightgrey/" -e "s/  :: / /" \
                     -e "s/&/&amp;/g"

# [ "$status" = "" ] && exit 0

# echo $status
