#!/usr/bin/env bash

[ -e /tmp/low_power_mode ] && exit 0

source /home/jacob/bin/_util
init-gems

case $button in
  1)
    xdg-open "https://darksky.net/forecast/$(geoclue)/us12/en" >/dev/null
    ;;
  2)
    /home/jacob/bin/weather --no-cache
    ;;
esac

icon=$(/home/jacob/bin/weather icon)
line=$(/home/jacob/bin/weather line)

if [ ! "$line" = "" ]; then
    pango_color "computer warrior" "<span weight='bold'>$icon</span> $line"
fi
