#!/bin/bash

source ~/bin/_util

case $BLOCK_BUTTON in
    1)
        nm-connection-editor
        ;;
esac

INTERFACE="${BLOCK_INSTANCE:-wlp4s0}"

if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]]; then
    echo "$(pango_color 'grey' '  WiFi off')"
    exit
fi

QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
SSID=$(iwgetid -r | sed 's/&/&amp;/')
#ADDR=$(hostname -I)

color () {
    local p=$1
    if [ "$p" -gt "50" ]; then
        local red=$(bc -l <<< "255 * 2 * (1 - ($p/100))")
        local green=255
    else
        local red=255
        local green=$(bc -l <<< "255 * 2 * ($p/100)")
    fi
    echo "#$(/home/jacob/code/dotfiles/bin/num2hex $red $green 0)"
}

echo -n "$(pango_color 'lavender' "  $SSID")"

if [[ "$QUALITY" -lt 70 ]]; then
    echo -n "$(pango_color "$(color "$QUALITY")" " $QUALITY%")"
fi

if nmcli c | grep vpn | grep wlp4s0 >/dev/null; then
    echo -n "$(pango_color 'bresnay' ' VPN')"
fi
