#!/bin/bash

source /home/jacob/bin/_util

case $button in
    1)
        nm-connection-editor
        ;;
esac

INTERFACE="${BLOCK_INSTANCE:-wlp4s0}"

refresh() {
    pkill -RTMIN+13 i3blocks
}

if [[ "$(cat /sys/class/net/$INTERFACE/operstate)" = 'down' ]]; then
    echo "$(pango_color 'red' '  WiFi off')"
    sleep 0.5
    refresh
    exit
fi

QUALITY=$(grep $INTERFACE /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
SSID=$(nmcli -t -f active,ssid dev wifi | grep '^yes' | cut -d: -f2 | sed 's/&/&amp;/')
#ADDR=$(hostname -I)

color () {
    local p=$1
    if [ "$p" -gt "50" ]; then
        local red=$(bc -l <<< "255 * 2 * (1 - ($p/100))")
        local green=255
    else
        local red=255
        local green=$(bc -l <<< "255 * 2 * ($p/100)")
    fi
    echo "#$(/home/jacob/code/dotfiles/bin/num2hex $red $green 0)"
}

pango_color 'lavender' " $SSID"

if [[ "$QUALITY" -lt 100 ]]; then
    pango_color "$(color "$QUALITY")" " $QUALITY%"
fi

if nmcli c | grep vpn | grep wlp4s0 >/dev/null; then
    pango_color 'bresnay' ' VPN'
fi
